# Generated by Django 5.0.14 on 2026-01-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptions_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
