# Generated by Django 5.0.14 on 2026-01-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_usersubscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
