# Generated by Django 5.0.14 on 2026-01-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_subscriptionsprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsprice',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionsprice',
            name='order',
            field=models.ImageField(default=-1, upload_to=''),
        ),
    ]
