# Generated by Django 5.0.14 on 2026-01-19 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_subscriptionsprice_featured_subscriptionsprice_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsprice',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionsprice',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
