# Generated by Django 5.0.14 on 2026-01-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_subscriptionsprice_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionsprice',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
