# Generated by Django 5.0.14 on 2026-01-19 21:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_alter_subscriptionsprice_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'ordering': ['order', 'featured', '-updated'], 'permissions': [('advanced', 'Advanced Per'), ('pro', 'Pro Per'), ('basic', 'Basic Per')]},
        ),
        migrations.AlterModelOptions(
            name='subscriptionsprice',
            options={'ordering': ['order', 'featured', '-updated']},
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='order',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
