# Generated by Django 5.0.14 on 2026-01-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_alter_subscriptions_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionsprice',
            options={'ordering': ['subscription__order', 'order', 'featured', '-updated']},
        ),
    ]
