# Generated by Django 5.0.14 on 2026-01-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_alter_subscriptionsprice_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
