# Generated by Django 5.0.14 on 2026-01-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_subscriptions_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='features',
            field=models.TextField(blank=True, help_text='Features for pricing, separated by new line.', null=True),
        ),
    ]
