# Generated by Django 5.0.14 on 2026-01-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_alter_subscriptions_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='subtitle',
            field=models.CharField(blank=True, null=True),
        ),
    ]
