# Generated by Django 5.0.14 on 2026-01-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_subscriptions_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptions',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
