# Generated by Django 5.0.14 on 2026-01-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_usersubscriptions_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptions',
            name='user_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
