# Generated by Django 5.0.14 on 2026-01-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_usersubscriptions_user_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptions',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscriptions',
            name='current_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
