# Generated by Django 5.0.14 on 2026-01-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0019_usersubscriptions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptions',
            name='original_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
